# Generated by Django 4.1.3 on 2023-05-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_remove_attendence_roll_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hod',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ManyToManyField(blank=True, to='home.department'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='department',
            field=models.ManyToManyField(blank=True, to='home.department'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subject'),
        ),
    ]
