# Generated by Django 4.1.3 on 2023-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='smester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
