# Generated by Django 4.1.3 on 2023-05-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_teachers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teachers'),
        ),
    ]
