# Generated by Django 4.1.3 on 2023-05-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_application_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_request',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application_request',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
