# Generated by Django 4.1.3 on 2023-05-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_application_request_created_at_pending_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='department',
        ),
        migrations.AddField(
            model_name='teachers',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
    ]
