# Generated by Django 4.1.3 on 2023-05-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_teachers_department_teachers_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='department',
        ),
        migrations.AddField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
    ]
