# Generated by Django 4.1.3 on 2023-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_hod_department_hod_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='media/student/pic.jpg', null=True, upload_to='student'),
        ),
    ]
